"""add_bank_enum_column

Revision ID: 904eb3f1c2b2
Revises: 5cf7db0c7681
Create Date: 2026-05-23 15:13:56.231466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.models.transaction import BankSource


# revision identifiers, used by Alembic.
revision: str = '904eb3f1c2b2'
down_revision: Union[str, Sequence[str], None] = '5cf7db0c7681'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bank_source_enum = sa.Enum('monobank', 'privatbank', name='banksource')
    bank_source_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'transactions',
        sa.Column(
            'bank',
            sa.Enum('monobank', 'privatbank', name='banksource'),
            nullable=False,
            server_default='monobank'
        )
    )
    op.add_column('transactions', sa.Column('mcc', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('commissions', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('transactions', sa.Column('cashback', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('transactions', sa.Column('exchange_rate', sa.Numeric(precision=10, scale=4), nullable=True))
    op.create_index(op.f('ix_transactions_bank'), 'transactions', ['bank'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_bank'), table_name='transactions')
    op.drop_column('transactions', 'exchange_rate')
    op.drop_column('transactions', 'cashback')
    op.drop_column('transactions', 'commissions')
    op.drop_column('transactions', 'mcc')
    op.drop_column('transactions', 'bank')
    bank_source_enum = sa.Enum('monobank', 'privatbank', name='banksource')
    bank_source_enum.drop(op.get_bind(), checkfirst=True)
