"""add category_rules table

Revision ID: b15f2c000860
Revises: 904eb3f1c2b2
Create Date: 2026-06-01 09:35:53.939495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b15f2c000860'
down_revision: Union[str, Sequence[str], None] = '904eb3f1c2b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('assigned_category', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_rules_id'), 'category_rules', ['id'], unique=False)
    op.create_index(op.f('ix_category_rules_keyword'), 'category_rules', ['keyword'], unique=False)
    op.create_index(op.f('ix_category_rules_owner_id'), 'category_rules', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_rules_owner_id'), table_name='category_rules')
    op.drop_index(op.f('ix_category_rules_keyword'), table_name='category_rules')
    op.drop_index(op.f('ix_category_rules_id'), table_name='category_rules')
    op.drop_table('category_rules')
    # ### end Alembic commands ###
